import Head from "next/head";
import Navbar from "../components/Navbar";
import Todo from "../components/Todo";
import { table, minifyRecords } from "./api/utils/airtable";
import { TodosContext } from "../contexts/TodosContext";
import React, { useEffect, useContext } from "react";
import TodoForm from "../components/TodoForm";
import { useUser } from "@auth0/nextjs-auth0";
import { withApiAuthRequired, getSession } from "@auth0/nextjs-auth0";
import auth0 from "./api/utils/auth0";

export default function Home({ initialTodos, user }) {
  console.log(user);
  const { todos, setTodos } = useContext(TodosContext);

  useEffect(() => {
    setTodos(initialTodos);
  }, []);

  console.log(initialTodos, "initialtodos");
  console.log(todos, "todos ");

  return (
    <div>
      <Head>
        <title>Authentecated ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl text-center mb-4 mt-4">My Todos</h1>

        {user ? (
          <>
            <TodoForm />
            <ul>
              {todos && todos.map((todo) => <Todo key={todo.id} todo={todo} />)}
            </ul>
          </>
        ) : (
          <p className="text-center mt-4">please login to save todos</p>
        )}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await auth0.getSession(context.req, context.res);
  let todos = [];

  try {
    if (session?.user) {
      todos = await table
        .select({
          filterByFormula: `userId = '${session.user.sub}'`,
        })
        .firstPage();
    }
    return {
      props: {
        initialTodos: minifyRecords(todos),
        user: session?.user || null,
      },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {
        err: "something went wrong",
      },
    };
  }
}
